# Generated by Django 3.2.19 on 2023-06-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_cloud_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Migraton_Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
